### ISSUE TITLE
Cannot use 0.7.2, 0.7.3 or 0.7.4-SNAPSHOT

### ISSUE THREAD

**Issue by azakhary** [kotcrab/VisEditor#3]
I am unable to use latest versions of VisUI, 
always getting error:

Could not resolve all dependencies for configuration ':compile'.
> Could not resolve com.kotcrab.vis:vis-ui:0.7.4-SNAPSHOT.
  Required by:
   > Could not parse POM https://oss.sonatype.org/content/repositories/snapshots/com/kotcrab/vis/vis-ui/0.7.4-SNAPSHOT/vis-ui-0.7.4-20150427.154831-2.pom
      > Could not find com.kotcrab.vis:vis-parent:0.0.2-SNAPSHOT.

And it seems others experienced similar issue.

is 0.0.2-SNAPSHOT in some other repo?

**Comment by kotcrab** [comment]
It's because I tried to simplify pom by moving some things to parent pom, but I'm not a Maven expert and expected that parent pom would be merged into VisUI pom but looks like it isn't...

I can't fix those versions, the workaround would be to clone this repo and execute `mvn install` (Maven required) in root or use those versions as jar dependencies.

I will fix this ASAP and deploy new release.

Sorry and thanks a lot for reporting this!

**Comment by azakhary** [comment]
Thanks! I just downloaded the jar as temp workaround.

**Comment by kotcrab** [comment]
VisUI 0.7.4 and 0.7.5-SNAPSHOT should work now.
